add former nimi.li-exclusive to sandbox
lipu-linku/sona pull request #63
Opened 2024-03-10 20:54 UTC by cubedhuang

i am unsure about a few things
- what should i do with `[usage]` since it has never (to my knowledge) been recorded? (i just left it empty)
  - actually i just realized that these were probably surveyed in 2023 - do we still have those results?
- what do i do with no `ligatures`? should i remove it or leave it empty (i left them empty)
- do i need to add empty `sp_etymology` and `commentary` entries or can i just add nothing? (i created empty entries)

2024-03-10 20:57 UTC, TheOnlyTails commented
All three of the things you listed were correct, just add an empty `audio` list to everything:
```toml
audio = []
```

2024-03-10 20:58 UTC, TheOnlyTails commented on words/metadata/aku.toml
> +
```suggestion
audio = []
```

2024-03-10 20:58 UTC, TheOnlyTails commented on words/metadata/anta.toml
> +
```suggestion
audio = []
```

2024-03-10 20:59 UTC, TheOnlyTails commented on words/metadata/inta.toml
> +
```suggestion
audio = []
```

2024-03-10 20:59 UTC, TheOnlyTails commented on words/metadata/iseki.toml
> +
```suggestion
audio = []
```

2024-03-10 20:59 UTC, TheOnlyTails commented on words/metadata/kana.toml
> +
```suggestion
audio = []
```

2024-03-10 20:59 UTC, TheOnlyTails commented on words/metadata/nowi.toml
> +
```suggestion
audio = []
```

2024-03-10 20:59 UTC, TheOnlyTails commented on words/metadata/sole.toml
> +
```suggestion
audio = []
```

2024-03-10 20:59 UTC, TheOnlyTails commented on words/metadata/ta.toml
> +
```suggestion
audio = []
```

2024-03-10 21:00 UTC, cubedhuang commented
a wait the other metadata things currently have a blank `[[audio]]` rather than a `audio = []`

should the format be consistent or is this fine?

2024-03-10 21:08 UTC, TheOnlyTails commented
If you were to do just a `[[audio]]`, it would be the equivalent of doing `audio = [{}]`, which isn't what we want.
We do it for the etymology field because we need to have the same number of items in both the localized and non-localized etymology fields.

2024-03-10 21:09 UTC, TheOnlyTails commented on words/translations/en/etymology.toml
> +[[insa]]
```suggestion
[[inta]]
```

2024-03-13 12:32 UTC, TheOnlyTails requested changes

2024-03-13 12:32 UTC, TheOnlyTails commented on words/source/sp_etymology.toml
> +ante = ""
```suggestion
anta = ""
```

2024-03-13 16:40 UTC, TheOnlyTails commented
did you forget aku somewhere?

2024-03-13 17:27 UTC, cubedhuang commented
i thought it was mad since i removed all the words from the `translations` folder, so now they're only in the `source` folder

should i leave both the `translations` and `source` entries?

2024-03-13 21:04 UTC, TheOnlyTails commented
no, i think we just need to figure out a way to have crowdin generate the translation files at build time

2024-03-28 22:56 UTC, gregdan3 approved these changes

2024-03-28 22:57 UTC, merged